spring:
  application:
    name: Hoover control

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8443}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    protocol: TLS
    enabled-protocols: TLSv1.2
#    TLS configuration manual https://www.baeldung.com/spring-tls-setup