version: '3'

services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/app/Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/hoover_control
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8443:8443"
    volumes:
      - ./app/logs:/APP/logs
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoover_control
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
